language: cpp
sudo: required
dist: trusty

cache: ccache

compiler:
  - gcc
  - clang

os:
  - linux
  - osx


env:
  - BUILD_TYPE="RelWithDebInfo"
  - BUILD_TYPE="Sanitize"

matrix:
  exclude:
    - compiler: gcc
      env: BUILD_TYPE="Sanitize"
    - os: osx
      env: BUILD_TYPE="Sanitize"

install:
  - sh setup_env.sh
